name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm clean-install
      - run: npm run lint
      - run: bash runtest.sh
      - uses: codecov/codecov-action@v2
        with:
          files: ./coverage/coverage-final.json,./coverage4/coverage-final.json
